services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.app
    ports:
      - "54321:54321"

  postgres:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
