services:
  app:
    build: .
    ports:
      - "54321:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:17.5-bullseye
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: