services:
  app-test:
    build: .
    command: go test ./... -tags=integration
    depends_on:
      - postgres-test

  postgres-test:
    image: postgres:17.5-bullseye
    env_file:
      - .env
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

volumes:
  postgres_data_test:
