#!/bin/bash

docker exec -it wrinkle-pg-1 psql -U postgres -f app/scripts/e2e-setup.sql
# docker compose restart proxy
docker exec wrinkle-proxy-1 go clean -testcache
docker exec wrinkle-proxy-1 go test ./e2e/... --tags="e2e"
